name: doc

on:
  push:
    branches:
      - dev
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: 'markdown-link-check.json'