site_name: System Software Team Home Page
site_url: https://tier4.github.io/system_software_team_hp
repo_url: https://github.com/tier4/system_software_team_hp
edit_uri: edit/main/
docs_dir: docs

theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  language: en
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  font:
    text: IBM Plex Sans
    code: Oxygen Mono
  version:
    provider: mike

extra_css:
  - https://unpkg.com/mermaid@8.13.10/dist/mermaid.css
  - assets/css/extra.css
  - https://use.fontawesome.com/releases/v5.15.4/css/all.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - awesome-pages
  - exclude:
      regex:
        - ^(?!(.*/)?assets/).*\.(?!(.*\.)?md|(.*\.)?svg|(.*\.)?png|(.*\.)?jpg).*$
        - ^(.*/)?[^.]*$
  - macros
  - same-dir
  - search
  - autorefs

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - fontawesome_markdown
  - footnotes
  - mdx_math
  - mdx_truly_sane_lists:
      nested_indent: 2
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
      format: svg
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"